spring:
  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    url: jdbc:postgresql://localhost:5432/air_company_db

server:
  port: 8080